#!/bin/bash
./match_up3.py params/gltcs_library_high_z/247.param 
./match_up3.py params/gltcs_library_high_z/241.param 
./match_up3.py params/gltcs_library_high_z/235.param 
./match_up3.py params/gltcs_library_high_z/230.param 
./match_up3.py params/gltcs_library_high_z/224.param 
./match_up3.py params/gltcs_library_high_z/219.param 
./match_up3.py params/gltcs_library_high_z/213.param 
./match_up3.py params/gltcs_library_high_z/208.param 
./match_up3.py params/gltcs_library_high_z/203.param 
./match_up3.py params/gltcs_library_high_z/198.param 
./match_up3.py params/gltcs_library_high_z/194.param 
./match_up3.py params/gltcs_library_high_z/189.param 
./match_up3.py params/gltcs_library_high_z/184.param 
./match_up3.py params/gltcs_library_high_z/180.param 
./match_up3.py params/gltcs_library_high_z/176.param 
./match_up3.py params/gltcs_library_high_z/171.param 
./match_up3.py params/gltcs_library_high_z/167.param 
./match_up3.py params/gltcs_library_high_z/163.param 
./match_up3.py params/gltcs_library_high_z/159.param 
./match_up3.py params/gltcs_library_high_z/155.param 
./match_up3.py params/gltcs_library_high_z/151.param 
./match_up3.py params/gltcs_library_high_z/148.param 
./match_up3.py params/gltcs_library_high_z/144.param 
./match_up3.py params/gltcs_library_high_z/141.param 
./match_up3.py params/gltcs_library_high_z/137.param 
./match_up3.py params/gltcs_library_high_z/134.param 
./match_up3.py params/gltcs_library_high_z/131.param 
./match_up3.py params/gltcs_library_high_z/127.param 
./match_up3.py params/gltcs_library_high_z/124.param 
./match_up3.py params/gltcs_library_high_z/121.param 
